### ISSUE TITLE
[REQ] fix license file

### ISSUE THREAD

**Issue by forart** [Amir-BK/unDAW#18]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/forart/HyMPS# ) \ [DAWs page](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#-- ) \ [Generic](https://github.com/forart/HyMPS/blob/main/Audio/DAWs.md#generic-)), can you please fix the license file for it ?

Although it may sounds like a minor aspect, license file uncompliance causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/Amir-BK/unDAW/)
(badge-generator URL: https://flat.badgen.net/github/license/Amir-BK/unDAW/)

For example, check the [Open Sound Refenation's (archived) git](https://github.com/OSRTeam/OpenSoundRefenation/blob/master/LICENSE) to visualize an example of how the MIT license needs to be formatted to let GH interprets it correctly. And, of course, its badge:

![](https://flat.badgen.net/github/license/OSRTeam/OpenSoundRefenation/)
(badge-generator URL: https://flat.badgen.net/github/license/OSRTeam/OpenSoundRefenation/)

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by Amir-BK** [comment]
Hey @forart ! I wasn't even aware I broke it, I think it's fixed now, the badge shows correctly in the preview as with the example you sent me. Thanks for the heads up and also for including the repo in your project and giving it some attention :)

**Comment by Amir-BK** [comment]
@forart with the way things are set up (although not all the controls are exposed) you'll be able to insert custom metasound patches into the instrument track (and use a custom metasound as an instrument, this has been shown in some past demos but currently as I re-wrote the widget it's not exposed) - so any metasound node or patch (custom or otherwise) can be used in the generated graph.

This is all done via the metasound builder system added by epic in ue 5.3.

**Comment by Amir-BK** [comment]
@forart Hey, I finally have audio inserts implemented and I tested GuitarEffectPlugin, to make things easier I also forked the original repo and wrapped it as its own plugin for ease of use - 
https://github.com/Amir-BK/UE5-GuitarPedalEffects-Plugin

https://youtu.be/WavBqhagsPQ - all in all it's pretty cool but from the video you can see that the guitar effects nodes only update their value when the graph is initialized, so they cannot receive real-time controls (the 'bitcrusher' node is not from GuitarEffectPlugin). It's probably an easy fix, there are also some metasound APIs that have deprecation warnings that can probably be adressed.

**Comment by Amir-BK** [comment]
well, fixed that as well! https://youtu.be/KeRaC3mzVz0

It turns out it's the unreal API upgrades that allow real time param bindings.
